services:
  client:
    build: ./client-api-springboot
    container_name: vite-client
    ports:
      - "5173:5173"
    networks:
      - cantina-network

networks:
  cantina-network:
    driver: bridge